### ISSUE TITLE
Cannot use namespace 'Tx' as a type

### ISSUE THREAD

**Issue by dapplion** [slockit/in3-common#3]
Issue https://github.com/slockit/in3-common/issues/1 is still relevant. Typescript compilation of the library fails due to a wrong use of `ethereumjs-tx` types.
```js
node_modules/in3-common/js/src/modules/eth/serialize.d.ts:162:19 - error TS2709: Cannot use namespace 'Tx' as a type.

162     transactions: Tx[];
                      ~~
Found 1 error.
```

Could it be that you are trying to use the `TxData` type exported by `'ethereumjs-tx'`? If that is the case changing `node_modules/in3-common/js/src/modules/eth/serialize.d.ts:36` with 

```js
import { TxData } from 'ethereumjs-tx';
```

and then `:162`

```js
transactions: TxData[];
```

fixed the problem and compilation succeeded

**Comment by simon-jentzsch** [comment]
Can you give me a hint how to reproduce it, since I can not get this error.

What is your typescript version?
What is your nodejs version?
Dow you have any other dependencies to ethereumjs-tx?

**Comment by dapplion** [comment]
I'm adding `in3` to this project https://github.com/dappnode/DNP_DAPPMANAGER @master
- `typescript@3.7.2`
- Node `v10.15.3`
```
lion@DNP_DAPPMANAGER/build/src$ npm ls ethereumjs-tx
dnp_dappmanager@0.1.0 dappnode/DNP_DAPPMANAGER/build/src
└─┬ eth-crypto@1.4.0
  └── ethereumjs-tx@2.1.0
```
However I'm getting mix results now where if I add to the package.json the dependency manually `"@types/ethereumjs-tx": "^2.0.0"` then it compiles fine

**Comment by junaidev** [comment]
Its fixed and the fix will be rolled out in next release in few days.
